import React from 'react';
import { TranslationProject, TranslationBlock } from '../types';
import { UI_STRINGS, LanguageCode } from '../services/i18n';
import { Heart, FileText, Download, ArrowRight, Trash2, X, FileDown, Archive } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

interface FavoritesPageProps {
  history: TranslationProject[];
  lang: LanguageCode;
  onNavigateToProject: (projectId: string, blockId: string) => void;
  onUpdateNote: (projectId: string, blockId: string, note: string) => void;
  onRemoveFavorite: (projectId: string, blockId: string) => void;
  onExportBackup: () => void; // Uses the main app backup function
  onClose: () => void;
}

const FavoritesPage: React.FC<FavoritesPageProps> = ({
  history,
  lang,
  onNavigateToProject,
  onUpdateNote,
  onRemoveFavorite,
  onExportBackup,
  onClose
}) => {
  const t = UI_STRINGS[lang];

  // Aggregate all favorites
  const allFavorites = history.flatMap(project => 
    project.blocks
      .filter(b => b.isFavorite)
      .map(b => ({
        block: b,
        projectMeta: project.metadata,
        projectId: project.id
      }))
  );

  // Export readable text (Markdown) for external use (Not for backup restoration)
  const exportFavoritesToMarkdown = () => {
    let content = `# ${t.favoritesTitle}\n\nGenerated by Translator Pro\n\n---\n\n`;
    
    allFavorites.forEach(({ block, projectMeta }) => {
        content += `### ${projectMeta.title} (${projectMeta.fandom})\n`;
        content += `> ${block.original}\n\n`;
        content += `${block.translated}\n\n`;
        if (block.note) {
            content += `*Note: ${block.note}*\n\n`;
        }
        content += `---\n\n`;
    });

    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `favorites_clippings_${new Date().toISOString().slice(0,10)}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-5xl mx-auto px-4 py-8 animate-in fade-in slide-in-from-bottom-4">
      <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 gap-4">
        <div>
           <h1 className="text-3xl font-bold text-gray-900 font-serif flex items-center gap-3">
              <Heart className="w-8 h-8 text-[#990000] fill-current" />
              {t.favoritesTitle}
           </h1>
           <p className="text-gray-500 mt-2">
              {allFavorites.length} {t.blocks} collected
           </p>
        </div>
        <div className="flex flex-wrap gap-3">
            {/* Full Backup Button */}
            <button 
                onClick={onExportBackup}
                className="flex items-center gap-2 px-4 py-2 bg-[#990000] text-white rounded-lg shadow-md hover:bg-[#800000] font-medium transition-colors"
                title="Saves history, favorites, and notes to a JSON file."
            >
                <Archive className="w-4 h-4" /> {t.exportFavorites}
            </button>
            
            {/* Readable MD Export */}
            <button 
                onClick={exportFavoritesToMarkdown}
                className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-200 rounded-lg shadow-sm hover:bg-gray-50 font-medium text-gray-700 transition-colors"
            >
                <FileDown className="w-4 h-4" /> {t.exportFavoritesMD}
            </button>

            <button 
                onClick={onClose}
                className="flex items-center gap-2 px-4 py-2 bg-gray-100 border border-transparent rounded-lg hover:bg-gray-200 font-medium text-gray-700 transition-colors"
            >
                <X className="w-4 h-4" /> Close
            </button>
        </div>
      </div>

      {allFavorites.length === 0 ? (
         <div className="text-center py-20 bg-white rounded-2xl border border-dashed border-gray-300">
             <Heart className="w-16 h-16 text-gray-200 mx-auto mb-4" />
             <p className="text-gray-500 text-lg">{t.noFavorites}</p>
         </div>
      ) : (
         <div className="grid gap-6">
            {allFavorites.map(({ block, projectMeta, projectId }) => (
               <div key={`${projectId}-${block.id}`} className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden hover:shadow-md transition-shadow">
                  <div className="p-6">
                      {/* Meta Header */}
                      <div className="flex justify-between items-start mb-4">
                          <div className="text-sm text-gray-500">
                              <span className="font-bold text-gray-900">{projectMeta.title}</span> 
                              <span className="mx-2">•</span> 
                              {projectMeta.author}
                              <span className="mx-2">•</span> 
                              <span className="bg-gray-100 px-1.5 py-0.5 rounded text-xs">{projectMeta.fandom}</span>
                          </div>
                          <div className="flex gap-2">
                              <button 
                                onClick={() => onNavigateToProject(projectId, block.id)}
                                className="text-xs flex items-center gap-1 text-blue-600 hover:text-blue-800 font-medium px-2 py-1 rounded hover:bg-blue-50 transition-colors"
                              >
                                  {t.goToSource} <ArrowRight className="w-3 h-3" />
                              </button>
                              <button 
                                onClick={() => onRemoveFavorite(projectId, block.id)}
                                className="text-gray-400 hover:text-red-500 p-1"
                                title={t.deleteFavorite}
                              >
                                  <Trash2 className="w-4 h-4" />
                              </button>
                          </div>
                      </div>

                      {/* Content */}
                      <div className="grid md:grid-cols-2 gap-6 mb-6">
                          <div className="font-serif-read text-gray-500 text-justify text-sm leading-relaxed border-l-2 border-gray-100 pl-4">
                              {block.original}
                          </div>
                          <div className="font-serif-read text-gray-900 text-justify text-lg leading-relaxed">
                               <ReactMarkdown components={{ p: ({node, ...props}) => <p {...props} className="mb-0" /> }}>
                                {block.translated}
                               </ReactMarkdown>
                          </div>
                      </div>

                      {/* Notes Section */}
                      <div className="bg-yellow-50/50 rounded-lg p-3 border border-yellow-100/50">
                          <div className="flex items-start gap-2">
                              <FileText className="w-4 h-4 text-yellow-600 mt-1 shrink-0" />
                              <textarea 
                                  value={block.note || ''}
                                  onChange={(e) => onUpdateNote(projectId, block.id, e.target.value)}
                                  placeholder={t.notePlaceholder}
                                  className="w-full bg-transparent border-none text-sm text-gray-700 placeholder-gray-400 focus:ring-0 resize-none leading-relaxed"
                                  rows={block.note ? Math.max(2, block.note.split('\n').length) : 1}
                              />
                          </div>
                      </div>
                  </div>
               </div>
            ))}
         </div>
      )}
    </div>
  );
};

export default FavoritesPage;